ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: 
  - name: ie
    version: 10..latest
  - name: microsoftedge
    version: latest
  - name: iphone
    version: [8.4, 9.1]
  - name: ipad
    version: [8.4, 9.1]
  - name: android
    version: 4.4..latest
